serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn=${external_secrets_role_arn}
metrics:
  service:
    enabled: true
serviceMonitor:
  enabled: true
  namespace: "${prometheus_namespace}"
